export type TGif = {
    type: string;
    slug: string;
    url: string;
    title: string;
    id?: string;
    bitly_url?: string;
    embed_url?: string;
    username?: string;
    source?: string;
    rating?: string;
    content_url?: string;
    user?: string;
    source_tld?: string;
    source_post_url?: string;
    update_datetime?: string;
    create_datetime?: string;
    import_datetime?: string;
    trending_datetime?: string;
    images?: any;
    alt_text?: string;
};
